### ISSUE TITLE
消耗内存巨大

### ISSUE THREAD

**Issue by mudebug77** [FaronBracy/RogueSharp#35]
一个400*400的地图寻路一次消耗1-2M 内存。同时多个怪物寻路导致内存不足,大概在1小时后。需要调用GC.Collect(); 才能回收内存。

**Comment by FaronBracy** [comment]
> A 400 * 400 map path finding consumes 1-2M memory at a time. At the same time, multiple monsters are finding a way to cause insufficient memory, about 1 hour later. GC.Collect (); needs to be called to reclaim memory.

There was an optimization in this commit https://github.com/FaronBracy/RogueSharp/commit/2549746d651a22377f24202b8d056830839ba9a0 that caches the graph and makes finding multiple paths from a source node much faster. I'm also currently working on an A* implementation for finding a single path quickly. In order to help you more I would need a link to your source code that has the issue you are seeing.

在此提交中进行了优化https://github.com/FaronBracy/RogueSharp/commit/2549746d651a22377f24202b8d056830839ba9a0缓存了图形并使得从源节点查找多个路径变得更快。我目前还正在研究A *实现，以快速找到一条路径。为了帮助您更多，我需要一个指向您正在遇到的问题的源代码的链接。

**Comment by mudebug77** [comment]
感谢,我从nuget下载的版本.换github的版本的到解决。

**Comment by FaronBracy** [comment]
> Thanks, I downloaded the version from nuget. Change to the github version to resolve.

If you still want to pull from nuget you can use the pre-release version `5.0.0-pre2` it should also have the fix.

如果仍然想从nuget中拉出，则可以使用预发行版本“ 5.0.0-pre2”，它也应该有此修复程序。
